export async function getProducts({ page = 1, limit = 8 } = {}) {
    const allProducts = [
        {
            id: "1",
            name: "Premium Headphones",
            price: 299.99,
            description: "High-quality noise-cancelling headphones with premium sound.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-2.jpeg", "/images/products/headphone-3.jpeg"],
            rating: 4,
            rate: 3.2,
            sold: 1000,
            oldprice: 399.99,
            reviews: 125,
            category: "electronics",
        },
        {
            id: "2",
            name: "Wireless Earbuds",
            price: 149.99,
            description: "True wireless earbuds with long battery life.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.1,
            sold: 500,
            oldprice: 159.99,
            reviews: 80,
            category: "electronics",
        },
        {
            id: "3",
            name: "Smart Watch Pro",
            price: 199.99,
            description: "Advanced smartwatch with health monitoring features.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.5,
            sold: 750,
            oldprice: 249.99,
            reviews: 200,
            category: "electronics",
        },
        {
            id: "4",
            name: "4K Ultra HD TV",
            price: 899.99,
            description: "55-inch 4K Smart TV with HDR support.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.3,
            sold: 300,
            oldprice: 999.99,
            reviews: 150,
            category: "electronics",
        },
        {
            id: "5",
            name: "Bluetooth Speaker",
            price: 79.99,
            description: "Portable waterproof speaker with 20-hour battery.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.0,
            sold: 1200,
            oldprice: 99.99,
            reviews: 300,
            category: "electronics",
        },
        {
            id: "6",
            name: "Gaming Laptop",
            price: 1299.99,
            description: "High-performance laptop with RTX graphics.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.7,
            sold: 200,
            oldprice: 1499.99,
            reviews: 180,
            category: "electronics",
        },
        {
            id: "7",
            name: "Fitness Tracker",
            price: 49.99,
            description: "Track your steps, heart rate, and sleep patterns.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 3,
            rate: 3.8,
            sold: 1500,
            oldprice: 59.99,
            reviews: 250,
            category: "electronics",
        },
        {
            id: "8",
            name: "DSLR Camera",
            price: 599.99,
            description: "Professional camera with 24MP sensor and 4K video.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.6,
            sold: 180,
            oldprice: 699.99,
            reviews: 220,
            category: "electronics",
        },
        {
            id: "9",
            name: "Wireless Keyboard",
            price: 59.99,
            description: "Ergonomic keyboard with silent mechanical switches.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.2,
            sold: 800,
            oldprice: 79.99,
            reviews: 160,
            category: "electronics",
        },
        {
            id: "10",
            name: "Noise Cancelling Earbuds",
            price: 179.99,
            description: "Premium earbuds with active noise cancellation.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.4,
            sold: 600,
            oldprice: 199.99,
            reviews: 190,
            category: "electronics",
        },
        {
            id: "11",
            name: "External SSD",
            price: 129.99,
            description: "1TB portable SSD with USB-C connectivity.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.8,
            sold: 400,
            oldprice: 149.99,
            reviews: 210,
            category: "electronics",
        },
        {
            id: "12",
            name: "Smart Home Hub",
            price: 89.99,
            description: "Control all your smart devices from one place.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 3,
            rate: 3.9,
            sold: 350,
            oldprice: 99.99,
            reviews: 140,
            category: "electronics",
        },
        {
            id: "13",
            name: "Premium Headphones",
            price: 299.99,
            description: "High-quality noise-cancelling headphones with premium sound.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-2.jpeg", "/images/products/headphone-3.jpeg"],
            rating: 4,
            rate: 3.2,
            sold: 1000,
            oldprice: 399.99,
            reviews: 125,
            category: "electronics",
        },
        {
            id: "14",
            name: "Wireless Earbuds",
            price: 149.99,
            description: "True wireless earbuds with long battery life.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.1,
            sold: 500,
            oldprice: 159.99,
            reviews: 80,
            category: "electronics",
        },
        {
            id: "15",
            name: "Smart Watch Pro",
            price: 199.99,
            description: "Advanced smartwatch with health monitoring features.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.5,
            sold: 750,
            oldprice: 249.99,
            reviews: 200,
            category: "electronics",
        },
        {
            id: "16",
            name: "4K Ultra HD TV",
            price: 899.99,
            description: "55-inch 4K Smart TV with HDR support.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.3,
            sold: 300,
            oldprice: 999.99,
            reviews: 150,
            category: "electronics",
        },
        {
            id: "17",
            name: "Bluetooth Speaker",
            price: 79.99,
            description: "Portable waterproof speaker with 20-hour battery.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.0,
            sold: 1200,
            oldprice: 99.99,
            reviews: 300,
            category: "electronics",
        },
        {
            id: "18",
            name: "Gaming Laptop",
            price: 1299.99,
            description: "High-performance laptop with RTX graphics.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.7,
            sold: 200,
            oldprice: 1499.99,
            reviews: 180,
            category: "electronics",
        },
        {
            id: "19",
            name: "Fitness Tracker",
            price: 49.99,
            description: "Track your steps, heart rate, and sleep patterns.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 3,
            rate: 3.8,
            sold: 1500,
            oldprice: 59.99,
            reviews: 250,
            category: "electronics",
        },
        {
            id: "20",
            name: "DSLR Camera",
            price: 599.99,
            description: "Professional camera with 24MP sensor and 4K video.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.6,
            sold: 180,
            oldprice: 699.99,
            reviews: 220,
            category: "electronics",
        },
        {
            id: "21",
            name: "Wireless Keyboard",
            price: 59.99,
            description: "Ergonomic keyboard with silent mechanical switches.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.2,
            sold: 800,
            oldprice: 79.99,
            reviews: 160,
            category: "electronics",
        },
        {
            id: "22",
            name: "Noise Cancelling Earbuds",
            price: 179.99,
            description: "Premium earbuds with active noise cancellation.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 4,
            rate: 4.4,
            sold: 600,
            oldprice: 199.99,
            reviews: 190,
            category: "electronics",
        },
        {
            id: "23",
            name: "External SSD",
            price: 129.99,
            description: "1TB portable SSD with USB-C connectivity.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 5,
            rate: 4.8,
            sold: 400,
            oldprice: 149.99,
            reviews: 210,
            category: "electronics",
        },
        {
            id: "24",
            name: "Smart Home Hub",
            price: 89.99,
            description: "Control all your smart devices from one place.",
            images: ["/images/products/headphone-1.jpeg", "/images/products/headphone-1.jpeg"],
            rating: 3,
            rate: 3.9,
            sold: 350,
            oldprice: 99.99,
            reviews: 140,
            category: "electronics",
        }
    ];

    const startIndex = (page - 1) * limit;
    const endIndex = startIndex + limit;
    const paginatedProducts = allProducts.slice(startIndex, endIndex);

    return {
        products: paginatedProducts,
        total: allProducts.length,
        totalPages: Math.ceil(allProducts.length / limit),
        currentPage: page,
    };
}

// Add this new function to get a single product by ID
export async function getProductById(id) {
    const { products } = await getProducts({ limit: 1000 }); // Get all products
    return products.find(product => product.id === id);
}